name: CI

on: [push, workflow_dispatch]

env:
  DEPLOY_PATH: /var/www/app
  # В теории можно собрать не только Vue-приложение, так как принцип сборки мало где отличается
  BUILD_SCRIPT: npm run build
  BUILD_SCRIPT_OUTPUT: dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v3
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: npm ci
      # Собираем приложение
      - name: Build Appliction
        run: $BUILD_SCRIPT
      # Доставляем собранное приложение на сервер
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.DEPLOY_SERVER_HOST }}
          port: ${{ vars.DEPLOY_SERVER_PORT }}
          username: ${{ vars.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1